import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialTable1790502384198 implements MigrationInterface {
    name = 'InitialTable1790502384198'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "branchs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "address" character varying NOT NULL, "city" character varying NOT NULL, "province" character varying NOT NULL, "phone_number" character varying NOT NULL, "status" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "PK_c2a14f542feef68e3968ce1766c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "role" character varying NOT NULL, "status" character varying NOT NULL, "token_version" integer NOT NULL DEFAULT '0', "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "branch_id" uuid, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_module_enum" AS ENUM('product', 'sale', 'customer', 'report', 'setting', 'purchase', 'shift', 'stock', 'user', 'supplier', 'program')`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('create', 'update', 'delete', 'login', 'logout', 'print_receipt')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "module" "public"."audit_logs_module_enum" NOT NULL, "action" "public"."audit_logs_action_enum" NOT NULL, "description" text NOT NULL, "activity_time" TIMESTAMP NOT NULL, "ip_address" character varying, "device_info" text, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "user_id" uuid, "branch_id" uuid, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "category_products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "PK_f0ced3e957f2edbbc572b171686" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "image" character varying, "status" boolean NOT NULL, "code" character varying NOT NULL, "stock" integer NOT NULL, "unit" character varying NOT NULL, "barcode" character varying NOT NULL, "purchase_price" integer NOT NULL, "sale_price" integer NOT NULL, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "categoryId" uuid, "branchId" uuid, CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."discount_npromo_type_promo_enum" AS ENUM('percentage', 'fixed', 'free', 'buy', 'special')`);
        await queryRunner.query(`CREATE TABLE "discount_npromo" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "promo_name" character varying NOT NULL, "type_promo" "public"."discount_npromo_type_promo_enum" NOT NULL, "promo_value" character varying NOT NULL, "expired" TIMESTAMP, "status" boolean NOT NULL, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "branch_id" uuid, "product_id" uuid, CONSTRAINT "PK_6cced1125c965374f5e222fa456" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" integer NOT NULL, "name" character varying NOT NULL, "email" character varying, "phone_number" character varying, "address" character varying, "loyalty_point" integer, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "UQ_2714af51e3f7dd42cf66eeb08d6" UNIQUE ("email"), CONSTRAINT "PK_28b53062261b996d9c99fa12404" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "point_loyalty" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "points" integer NOT NULL, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "member_id" uuid, CONSTRAINT "PK_828ad75c0695bd303ff727120c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "financial_statement" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "date_report" TIMESTAMP NOT NULL, "total_income" integer NOT NULL, "total_expenditure" integer NOT NULL, "net_profit" integer NOT NULL, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "branch_id" uuid, CONSTRAINT "PK_4e795d12a43006ece4788e13371" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sales_report" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "date_report" TIMESTAMP NOT NULL, "total_sales" integer NOT NULL, "total_income" integer NOT NULL, "total_discount" integer NOT NULL, "total_tax" integer NOT NULL, "total_profit" integer NOT NULL, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "branch_id" uuid, CONSTRAINT "PK_b10b439945b1bad04adf9409874" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "initial_stock" integer NOT NULL, "stock_sold" integer NOT NULL, "stock_in" integer NOT NULL, "remaining_stock" integer NOT NULL, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "product_id" uuid, "branch_id" uuid, CONSTRAINT "PK_19dabe7a7ba7d325fc818959132" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_method" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "status" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "PK_7744c2b2dd932c9cf42f2b9bc3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sales_managements_status_payment_enum" AS ENUM('finished', 'pending', 'canceled')`);
        await queryRunner.query(`CREATE TABLE "sales_managements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transaction_number" character varying NOT NULL, "total_price" integer NOT NULL, "tax" integer, "discount" integer, "total_payment" integer NOT NULL, "method_payment" character varying NOT NULL, "status_payment" "public"."sales_managements_status_payment_enum" NOT NULL, "transaction_time" character varying NOT NULL, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "cashier_id" uuid, "branch_id" uuid, CONSTRAINT "PK_6d1166e1b1bb4fbee839122a790" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sales_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" integer NOT NULL, "unit_price" integer NOT NULL, "total_price" integer NOT NULL, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "sales_id" uuid, "product_id" uuid, CONSTRAINT "PK_347905aa7874a8beb27680a8709" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "general_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "store_name" character varying NOT NULL, "address" character varying NOT NULL, "phone_number" character varying NOT NULL, "email" character varying NOT NULL, "logo" character varying NOT NULL, "tax" integer NOT NULL, "global_discount" integer NOT NULL, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "PK_c3b79ecb7c2446f3ba18a07f8e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_access_rights_modules_enum" AS ENUM('product', 'report', 'customer', 'audit', 'branch', 'program', 'sales', 'setting', 'shift', 'supply', 'stock', 'user')`);
        await queryRunner.query(`CREATE TYPE "public"."user_access_rights_action_enum" AS ENUM('create', 'read', 'update', 'delete')`);
        await queryRunner.query(`CREATE TABLE "user_access_rights" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "modules" "public"."user_access_rights_modules_enum" array NOT NULL, "action" "public"."user_access_rights_action_enum" NOT NULL, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "user_id" uuid, "branch_id" uuid, CONSTRAINT "PK_0128802ff7f32b32da34d0a1997" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."shifts_shift_status_enum" AS ENUM('active', 'closed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "shifts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "time_in" character varying NOT NULL, "time_out" character varying, "total_sales" numeric(12,2) NOT NULL DEFAULT '0', "total_transactions" integer NOT NULL DEFAULT '0', "opening_cash" numeric(12,2) NOT NULL DEFAULT '0', "closing_cash" numeric(12,2), "shift_note" text, "shift_status" "public"."shifts_shift_status_enum" NOT NULL DEFAULT 'active', "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "branch_id" uuid, "cashier_id" uuid, CONSTRAINT "PK_84d692e367e4d6cdf045828768c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."shift_activity_logs_activity_type_enum" AS ENUM('sale', 'return', 'stock_transfer', 'transaction_cancel', 'other')`);
        await queryRunner.query(`CREATE TABLE "shift_activity_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activity_type" "public"."shift_activity_logs_activity_type_enum" NOT NULL, "description" text NOT NULL, "activity_time" TIMESTAMP NOT NULL, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "shift_id" uuid, CONSTRAINT "PK_f5f13b521f2858c2a6eee72686a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."mutation_stock_type_enum" AS ENUM('in', 'out', 'damaged', 'return')`);
        await queryRunner.query(`CREATE TABLE "mutation_stock" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."mutation_stock_type_enum" NOT NULL, "amount" integer NOT NULL, "remaining_stock" integer NOT NULL, "mutation_date" TIMESTAMP NOT NULL, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "product_id" uuid, "branch_id" uuid, CONSTRAINT "PK_500680a19600d366c8892252c07" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."return_of_goods_type_enum" AS ENUM('to_customer', 'to_supplier')`);
        await queryRunner.query(`CREATE TABLE "return_of_goods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" integer NOT NULL, "reason" character varying NOT NULL, "type" "public"."return_of_goods_type_enum" NOT NULL, "return_date" TIMESTAMP NOT NULL, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "product_id" uuid, "branch_id" uuid, CONSTRAINT "PK_0039ef3bad62ab79a327ef3ea0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "supply_management" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supplier_name" character varying NOT NULL, "contact" character varying NOT NULL, "address" character varying NOT NULL, "email" character varying NOT NULL, "status" boolean NOT NULL DEFAULT true, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "UQ_21b70efad0d98f88e801d5ea49d" UNIQUE ("email"), CONSTRAINT "PK_52f9a289f38049b4ac668a24fc7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_product_purchase_status_enum" AS ENUM('finished', 'pending')`);
        await queryRunner.query(`CREATE TABLE "purchase_product" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "total_price" integer NOT NULL, "purchase_date" TIMESTAMP NOT NULL, "purchase_status" "public"."purchase_product_purchase_status_enum" NOT NULL, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "supplier_id" uuid, "branch_id" uuid, CONSTRAINT "PK_70f3fd21152b586eb4ceae61c43" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "detail_purchase" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" integer NOT NULL, "unit_Price" integer NOT NULL, "sub_total" integer NOT NULL, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "purchase_id" uuid, "product_id" uuid, CONSTRAINT "PK_780150b581d7b146a2cb70e85bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_5a58f726a41264c8b3e86d4a1de" FOREIGN KEY ("branch_id") REFERENCES "branchs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_ee4c6baac8b07dc19433e575cb8" FOREIGN KEY ("branch_id") REFERENCES "branchs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ff56834e735fa78a15d0cf21926" FOREIGN KEY ("categoryId") REFERENCES "category_products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_dd1b22e313f7e7d28805557261f" FOREIGN KEY ("branchId") REFERENCES "branchs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_npromo" ADD CONSTRAINT "FK_f4e39d5ff33a3dfcc0132c0be5d" FOREIGN KEY ("branch_id") REFERENCES "branchs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_npromo" ADD CONSTRAINT "FK_cb3416792da35caac0b77bb0e18" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "point_loyalty" ADD CONSTRAINT "FK_8f45d41700de9b004069c6a649d" FOREIGN KEY ("member_id") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "financial_statement" ADD CONSTRAINT "FK_4ed7ff5a30f69b3aa627a4d8139" FOREIGN KEY ("branch_id") REFERENCES "branchs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_report" ADD CONSTRAINT "FK_977546cdc1247343011cc022ba4" FOREIGN KEY ("branch_id") REFERENCES "branchs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_reports" ADD CONSTRAINT "FK_365457ef1d04ac40d1dfd8dd613" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_reports" ADD CONSTRAINT "FK_4ae8b35ed0f3eecd52d8cdde128" FOREIGN KEY ("branch_id") REFERENCES "branchs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_managements" ADD CONSTRAINT "FK_4e4046c64fda5f64171b3842c94" FOREIGN KEY ("cashier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_managements" ADD CONSTRAINT "FK_d4990a97695ed7a91c6940ad53c" FOREIGN KEY ("branch_id") REFERENCES "branchs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_details" ADD CONSTRAINT "FK_85f43ec60f02726830118ec59f5" FOREIGN KEY ("sales_id") REFERENCES "sales_managements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_details" ADD CONSTRAINT "FK_3b8a57faaababc72063ac2ef82b" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_access_rights" ADD CONSTRAINT "FK_ce8adefa03b68c7e6a077310da7" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_access_rights" ADD CONSTRAINT "FK_9ee9818e07cb53f0b5551fe5277" FOREIGN KEY ("branch_id") REFERENCES "branchs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shifts" ADD CONSTRAINT "FK_cddc0af590dd113d6e5b6b530c8" FOREIGN KEY ("branch_id") REFERENCES "branchs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shifts" ADD CONSTRAINT "FK_4fa09367d77edf0c10800aaf038" FOREIGN KEY ("cashier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift_activity_logs" ADD CONSTRAINT "FK_be609885372d1baee66a28b56d5" FOREIGN KEY ("shift_id") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mutation_stock" ADD CONSTRAINT "FK_decefe55236ef39809667e573a0" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mutation_stock" ADD CONSTRAINT "FK_d8c7324e36d482244b14e446685" FOREIGN KEY ("branch_id") REFERENCES "branchs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "return_of_goods" ADD CONSTRAINT "FK_15a4e96431f7f0302027c405b03" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "return_of_goods" ADD CONSTRAINT "FK_ede4fd34036769a40970d1afa24" FOREIGN KEY ("branch_id") REFERENCES "branchs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_product" ADD CONSTRAINT "FK_126bb90e48cf0c63c31e5a53231" FOREIGN KEY ("supplier_id") REFERENCES "supply_management"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_product" ADD CONSTRAINT "FK_5347c2a3449792cc6209e62e001" FOREIGN KEY ("branch_id") REFERENCES "branchs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detail_purchase" ADD CONSTRAINT "FK_4f975048e2bf3f270808eae8d81" FOREIGN KEY ("purchase_id") REFERENCES "purchase_product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detail_purchase" ADD CONSTRAINT "FK_ff2ae1ca0ec6c0d4be916b4e0c1" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "detail_purchase" DROP CONSTRAINT "FK_ff2ae1ca0ec6c0d4be916b4e0c1"`);
        await queryRunner.query(`ALTER TABLE "detail_purchase" DROP CONSTRAINT "FK_4f975048e2bf3f270808eae8d81"`);
        await queryRunner.query(`ALTER TABLE "purchase_product" DROP CONSTRAINT "FK_5347c2a3449792cc6209e62e001"`);
        await queryRunner.query(`ALTER TABLE "purchase_product" DROP CONSTRAINT "FK_126bb90e48cf0c63c31e5a53231"`);
        await queryRunner.query(`ALTER TABLE "return_of_goods" DROP CONSTRAINT "FK_ede4fd34036769a40970d1afa24"`);
        await queryRunner.query(`ALTER TABLE "return_of_goods" DROP CONSTRAINT "FK_15a4e96431f7f0302027c405b03"`);
        await queryRunner.query(`ALTER TABLE "mutation_stock" DROP CONSTRAINT "FK_d8c7324e36d482244b14e446685"`);
        await queryRunner.query(`ALTER TABLE "mutation_stock" DROP CONSTRAINT "FK_decefe55236ef39809667e573a0"`);
        await queryRunner.query(`ALTER TABLE "shift_activity_logs" DROP CONSTRAINT "FK_be609885372d1baee66a28b56d5"`);
        await queryRunner.query(`ALTER TABLE "shifts" DROP CONSTRAINT "FK_4fa09367d77edf0c10800aaf038"`);
        await queryRunner.query(`ALTER TABLE "shifts" DROP CONSTRAINT "FK_cddc0af590dd113d6e5b6b530c8"`);
        await queryRunner.query(`ALTER TABLE "user_access_rights" DROP CONSTRAINT "FK_9ee9818e07cb53f0b5551fe5277"`);
        await queryRunner.query(`ALTER TABLE "user_access_rights" DROP CONSTRAINT "FK_ce8adefa03b68c7e6a077310da7"`);
        await queryRunner.query(`ALTER TABLE "sales_details" DROP CONSTRAINT "FK_3b8a57faaababc72063ac2ef82b"`);
        await queryRunner.query(`ALTER TABLE "sales_details" DROP CONSTRAINT "FK_85f43ec60f02726830118ec59f5"`);
        await queryRunner.query(`ALTER TABLE "sales_managements" DROP CONSTRAINT "FK_d4990a97695ed7a91c6940ad53c"`);
        await queryRunner.query(`ALTER TABLE "sales_managements" DROP CONSTRAINT "FK_4e4046c64fda5f64171b3842c94"`);
        await queryRunner.query(`ALTER TABLE "stock_reports" DROP CONSTRAINT "FK_4ae8b35ed0f3eecd52d8cdde128"`);
        await queryRunner.query(`ALTER TABLE "stock_reports" DROP CONSTRAINT "FK_365457ef1d04ac40d1dfd8dd613"`);
        await queryRunner.query(`ALTER TABLE "sales_report" DROP CONSTRAINT "FK_977546cdc1247343011cc022ba4"`);
        await queryRunner.query(`ALTER TABLE "financial_statement" DROP CONSTRAINT "FK_4ed7ff5a30f69b3aa627a4d8139"`);
        await queryRunner.query(`ALTER TABLE "point_loyalty" DROP CONSTRAINT "FK_8f45d41700de9b004069c6a649d"`);
        await queryRunner.query(`ALTER TABLE "discount_npromo" DROP CONSTRAINT "FK_cb3416792da35caac0b77bb0e18"`);
        await queryRunner.query(`ALTER TABLE "discount_npromo" DROP CONSTRAINT "FK_f4e39d5ff33a3dfcc0132c0be5d"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_dd1b22e313f7e7d28805557261f"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ff56834e735fa78a15d0cf21926"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_ee4c6baac8b07dc19433e575cb8"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_5a58f726a41264c8b3e86d4a1de"`);
        await queryRunner.query(`DROP TABLE "detail_purchase"`);
        await queryRunner.query(`DROP TABLE "purchase_product"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_product_purchase_status_enum"`);
        await queryRunner.query(`DROP TABLE "supply_management"`);
        await queryRunner.query(`DROP TABLE "return_of_goods"`);
        await queryRunner.query(`DROP TYPE "public"."return_of_goods_type_enum"`);
        await queryRunner.query(`DROP TABLE "mutation_stock"`);
        await queryRunner.query(`DROP TYPE "public"."mutation_stock_type_enum"`);
        await queryRunner.query(`DROP TABLE "shift_activity_logs"`);
        await queryRunner.query(`DROP TYPE "public"."shift_activity_logs_activity_type_enum"`);
        await queryRunner.query(`DROP TABLE "shifts"`);
        await queryRunner.query(`DROP TYPE "public"."shifts_shift_status_enum"`);
        await queryRunner.query(`DROP TABLE "user_access_rights"`);
        await queryRunner.query(`DROP TYPE "public"."user_access_rights_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_access_rights_modules_enum"`);
        await queryRunner.query(`DROP TABLE "general_settings"`);
        await queryRunner.query(`DROP TABLE "sales_details"`);
        await queryRunner.query(`DROP TABLE "sales_managements"`);
        await queryRunner.query(`DROP TYPE "public"."sales_managements_status_payment_enum"`);
        await queryRunner.query(`DROP TABLE "payment_method"`);
        await queryRunner.query(`DROP TABLE "stock_reports"`);
        await queryRunner.query(`DROP TABLE "sales_report"`);
        await queryRunner.query(`DROP TABLE "financial_statement"`);
        await queryRunner.query(`DROP TABLE "point_loyalty"`);
        await queryRunner.query(`DROP TABLE "members"`);
        await queryRunner.query(`DROP TABLE "discount_npromo"`);
        await queryRunner.query(`DROP TYPE "public"."discount_npromo_type_promo_enum"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "category_products"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_module_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "branchs"`);
    }

}
